name: Unethicalite - Dev (push)

on:
  push:
    branches:
      - development
      - master

jobs:
  build:
    name: Build and bootstrap
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Assembling
        run: ./gradlew assemble --console=plain

      - name: Building
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain

      - name: Bootstrap
        run: ./gradlew bootstrapNightly -x test -x checkstyleMain --console=plain

      - name: Push to hosting
        run: |
          git clone https://sandymandy12:${{ secrets.AUTH_TOKEN }}@github.com/sandymandy12/unethical-plugins-host.git hosting
          cp ./runelite-client/build/bootstrap/nightly/runelite-client-*-SNAPSHOT.jar ./hosting
          cd hosting
          
          git config --global user.email "sandmand7546@yahoo.com"
          git config --global user.name "Github Actions"
          git add -A
          git commit -m 'client: auto release'
          git push https://sandymandy12:${{ secrets.AUTH_TOKEN }}@github.com/sandymandy12/unethical-plugins-host.git main



